require "unbelievable/core_ext/array"
require "unbelievable/version"
require "unbelievable/generator"
require "unbelievable/buzzwords"
require "unbelievable/foia"
require "unbelievable/haiku"
require "unbelievable/lorem"
require "unbelievable/magic"
