require "unbelievable/core_ext/array"
require "unbelievable/version"
require "unbelievable/generator"
require "unbelievable/haiku"
require "unbelievable/lorem"
require "unbelievable/secret"
require "unbelievable/todo"
require "unbelievable/magic"
